name: SonarQube CI/CD (.NET + SonarCloud + Artifact)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Analyze, Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # ✅ dùng đúng SDK mà project bạn cần

      - name: Setup JDK (SonarCloud requirement)
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: SonarScanner Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner begin /k:"nhat-trieu_devops" /o:"nhat-trieu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Solution
        run: dotnet build Project_BanSach.sln

      - name: SonarScanner End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Publish .NET App
        run: dotnet publish Project_BanSach/Project_BanSach.csproj -c Release -o ./publish

      - name: Zip artifact
        run: zip -r app.zip ./publish

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./app.zip
